README.md
=> Issue #7: Initial README file.

registryonsteroids.module
=> #21: rename drupal_*() functions 

registryonsteroids.module
=> #23: Rename _theme_post_process_registry()

registryonsteroids.module
=> #25: rename local variables

registryonsteroids.module
quite unrelated stuff, which I did not want to create separate PRs for.
Read the distinct commit messages.
Fixes #27.
=> #27: various CS improvements

registryonsteroids.module
=> #26: (CS) Add @param and @return docs on hook implementations.

registryonsteroids.module
=> #36: (bugfix) Do not overwrite $prefix in foreach body in _registryonsteroids_theme_find_processors()

tests/fixtures/core/render/render.yml, tests/fixtures/ros/render/render.yml, tests/src/Kernel/CoreRegistryDefinitionsTest.php, tests/src/Kernel/RegistryDefinitionsTest.php
Fixes #41, again, if we reopen it before :)
(Didn't want to open yet another issue)
=> #41: more linebreaks in yml

tests/fixtures/core/render/render.yml, tests/fixtures/ros/render/render.yml, tests/modules/ros_test/ros0.tpl.php, tests/modules/ros_test/ros1.tpl.php, tests/themes/ros_theme/ros2.tpl.php
Fixes #56.
For now we only have templates, no theme functions.
=> #56: tests append template or theme function

tests/fixtures/core/registry/registry.yml, tests/fixtures/core/render/render.yml, tests/fixtures/ros/registry/registry.yml, tests/fixtures/ros/render/render.yml, tests/modules/ros_test/ros_test.module
=> #51: Test other modules implementing hook_theme_registry_alter()

composer.json
=> Issue #64: Include a patch to prevent warnings with PHP 7.2.

registryonsteroids.module
=> Issue #67: Move code from global scope into a hook function.

composer.json
=> Issue #78: Update patch for PHP 7.2.

composer.json
=> Issue #80: Cleanup the composer.json file.

README.md, modules/registryonsteroids_alter/registryonsteroids_alter.info
=> Hide submodule and update README.

composer.json
=> Issue #86: Update url to patch.

composer.json
=> Issue #90: Update patch for PHP 7.2.

registryonsteroids.module, src/ThemeRegistryAltererFirst.php, src/ThemeRegistryAltererLast.php
=> Issue #102: Move file inclusion code section into the class.

runner.yml.dist
=> Issue #100: Update Runner configuration

README.md, registryonsteroids.module, tests/modules/ros_test/ros_test.info, tests/themes/ros_theme/ros_theme.info
=> Issue #98: Fix the typo in the module's name.

registryonsteroids.install
=> Issue #96: Make sure the weight is the heaviest.

registryonsteroids.info
=> Issue #105: Use "alternatives" contrib module is available.

registryonsteroids.install
=> Issue #96: Update module weight

modules/registryonsteroids_alter/README.md, modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc, modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc, modules/registryonsteroids_alter/registryonsteroids_alter.info, modules/registryonsteroids_alter/registryonsteroids_alter.module
=> Issue #92: Submodule "registryonsteroids_alter" code cleanup and refactoring.

composer.json, ruleset.xml
=> Issue #111: Replace ec-europa/qa-automation with drupal/coder.

modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc, modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc, modules/registryonsteroids_alter/registryonsteroids_alter.module, registryonsteroids.admin.inc, registryonsteroids.install, registryonsteroids.module, src/FunctionGroupUtil.php, src/ThemeHookStub.php, src/ThemeHookStubFactory.php, src/ThemeRegistryAltererFirst.php, tests/modules/ros_test/ros_test.module, tests/src/Kernel/AbstractThemeTest.php, tests/src/Kernel/CoreRegistryDefinitionsTest.php, tests/src/Kernel/RegistryDefinitionsTest.php
=> Issue #120: Convert arrays to the short syntax.

modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc, registryonsteroids.admin.inc, registryonsteroids.info, registryonsteroids.module
=> Issue #113: Update documentation, fix typos and function signatures.

src/ThemeRegistryAltererFirst.php, tests/fixtures/ros/registry/intermediate.yml, tests/fixtures/ros/registry/registry.yml, tests/themes/ros_theme/ros2--variant2--foo.tpl.php, tests/themes/ros_theme/template.php
=> Issue #131: Add missing callbacks.

modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
=> #122: Theme wrappers can be a nested array.

modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
=> Issue #122: Follow-up

modules/registryonsteroids_alter/registryonsteroids_alter.info
=> Issue #135: Hide the submodule until it's ready.

modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc, modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
=> Issue #137: Update the alter hooks mechanisms.

README.md
=> Issue #94: Update the README - Avoid confusions with ROS and Drupal's default behavior

tests/fixtures/ros/renderarray/elements.yml, tests/src/Kernel/AbstractThemeTest.php, tests/src/Kernel/RenderArrayAlterTest.php
Fix #127
This will require #123 and #134 in order to work.
=> Issue #127: Implement basic tests for alter submodule.

tests/fixtures/core/registry/registry.yml, tests/fixtures/core/render/render.yml, tests/fixtures/ros/registry/intermediate.yml, tests/fixtures/ros/registry/registry.yml, tests/fixtures/ros/render/render.yml, tests/modules/ros_test/ros_test.module, tests/src/Kernel/AbstractThemeTest.php, tests/themes/ros_theme/template.php
=> Issue #139: Tests theme hooks (and variants) using theme functions.

registryonsteroids.install
=> Issue #143: Make sure that hook_requirements returns an array instead of null

modules/registryonsteroids_alter_contrib/README.md, modules/registryonsteroids_alter_contrib/registryonsteroids_alter_contrib.info, modules/registryonsteroids_alter_contrib/registryonsteroids_alter_contrib.module, modules/registryonsteroids_alter_contrib/views/views.inc
=> Issue #146: Implementation of alter hooks for contrib modules.

modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc
=> Issue #153: Make sure the menu module is enabled before using menu_*() functions.

modules/registryonsteroids_alter/registryonsteroids_alter.menu.inc
=> Issue #155: Update the menu workflow - optimize performance.

modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
=> #159: Do not process empty menu trees

modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
=> #160: Only recurse menu trees, not menu links.

modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc, modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc, modules/registryonsteroids_alter/registryonsteroids_alter.menu.inc
=> Issue #165: Improve and optimize the menu blocks alteration.
